kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lnmp-redis-data
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: redis
      env: production
  storageClassName: "hostpath"
