resources:
- configMap.yaml
- csi-nfs-driverinfo.yaml
- csi-nodeplugin-nfsplugin.yaml
- csi-nodeplugin-rbac.yaml
- namespace.yaml
vars:
- name: KUBELET_ROOT
  objref:
    kind: ConfigMap
    name: csi.nfs.conf
    apiVersion: v1
  fieldref:
    fieldpath: data.kubelet_root
namespace: csi-nfs
