apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs-demo
spec:
  gateways:
  - demo-gw
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: nginx
        subset: v2
      weight: 100
    mirror:
      host: nginx
      subset: v1
    mirror_percent: 100

# 请求路由到 v2 ，查看 v1 容器也有日志输出
# curl -H "foo: bar" http://wsl2:19749/
