version: "3.7"

services:
  nginx:
    restart: always
    image: khs1994/nginx:1.17.3-windowsservercore-1903
    volumes:
      - ./windows/config/nginx:C:/nginx/conf/conf.d
      - ./config/nginx/demo-ssl:C:/nginx/conf/conf.d/ssl
      - ./app:C:/Users/90621/lnmp/app
    ports:
      - "8080:80"
      - "443:443"
    isolation: hyperv

  mysql:
    image: khs1994/mysql:8.0.17-windowsservercore-1903
    isolation: process # hyperv
    ports:
      - "3306:3306"

  php:
    restart: always
    image: khs1994/php:7.3.11-windowsservercore-1903
    isolation: hyperv
    volumes:
      - ./app:C:/Users/90621/lnmp/app
      - ./config/php:C:/phpconfig

networks:
  default:
    external:
      name: nat
