secretGenerator:
  - name: harbor-clair
    files:
    - config.yaml
    literals:
    - redis=redis://harbor-redis:6379/4
    - database=postgres://postgres:changeit@harbor-database:5432/postgres?sslmode=disable
generatorOptions:
  disableNameSuffixHash: true
