version: "3.7"

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mariadb:
    << : *default-common
    image: mariadb:${LNMP_MARIADB_VERSION:-10.5.3}
