version: "3.7"

#
# self build image compose file
#
# $ cd dockerfile/soft
#
# $ cp example.Dockerfile Dockerfile
#
# $ vi Dockerfile
#
# $ cd ../../
#
# $ ./lnmp-docker build [soft]
#

x-build:
  &default-build
  # Dockerfile: my.Dockerfile
  args:
    ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org

x-build-debian:
  &default-build-debian
  # Dockerfile: my.Dockerfile
  args:
    DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
    DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org

x-labels:
  &default-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=self_build

services:
  mysql:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build-debian
      context: ./dockerfile/mysql/

  redis:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/redis/

  php7:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/php/
    environment:
      - LNMP_DOCKER_VERSION=${LNMP_DOCKER_VERSION:-v19.03} x86_64 With Build Docker Image

  nginx:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/nginx/

  phpmyadmin:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build
      # << : *default-build-debian
      context: ./dockerfile/phpmyadmin/

networks:
  frontend:
    << : *default-labels
  backend:
    << : *default-labels

volumes:
  mysql-data:
    << : *default-labels
  redis-data:
    << : *default-labels
  zoneinfo-data:
    << : *default-labels
  phpmyadmin-data:
    << : *default-labels
  composer-cache-data:
    << : *default-labels
  mutagen-wsl2-data:
    << : *default-labels

secrets:
  db_root_password:
    << : *default-labels
    file: ./secrets/${LNMP_DB_ROOT_PASSWORD_PATH:-db_root_password.txt}
  supervisord_ini:
    << : *default-labels
    file: ./config/supervisord/${LNMP_SUPERVISORD_INI_PATH:-supervisord.ini}
