version: "3"

services:

  ruby:
     build:
       context: ruby
       args:
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
     image: khs1994/builder:ruby

  python:
     build:
       context: python
       args:
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
     image: khs1994/builder:python
