apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs-demo
spec:
  gateways:
  - demo-gw
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: nginx
        subset: v2
      weight: 50
    - destination:
        host: nginx
        subset: v1
      weight: 50

# 各有 50% 的流量到 v1、v2
# curl -H "foo: bar" http://wsl2:19749/
