version: '3.7'
services:

  alpine:
    build:
      context: ./alpine
      args:
        # OPENSSL_BRANCH: master
        NGINX_VERSION: ${NGINX_VERSION:-1.19.0}
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
        OPENSSL_URL: https://gitee.com/mirrors/boringssl
    image: khs1994/nginx:${NGINX_VERSION:-1.19.0}-alpine
    ports:
      - 443:443/tcp
      - 443:443/udp
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro

  buster:
    build:
      context: ./buster
      args:
        # OPENSSL_BRANCH: master
        NGINX_VERSION: ${NGINX_VERSION:-1.19.0}
        OPENSSL_URL: https://gitee.com/mirrors/boringssl
        DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
        DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security # security.debian.org/debian-security
    image: khs1994/nginx:${NGINX_VERSION:-1.19.0}-buster
    ports:
      - 443:443/tcp
      - 443:443/udp
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro

  official:
    image: nginx:1.19.0-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
