name: containerd
version: 1.3.4
url: "https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}.linux-amd64.tar.gz"
scripts:
  platform-reqs: if(!$IsLinux){echo $False}
  download: |
    _mkdir $env:LWPM_PKG_ROOT/dist

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/$filename
platform:
  - architecture: amd64
    os: linux
