version: "3.7"

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  nginx-unit:
    << : *default-common
    image: khs1994/php:${LNMP_PHP_VERSION:-7.4.7}-unit-alpine
