version: "3.7"

x-common:
  &default-common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &default-common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  nginx-unit:
    << : *default-common
    image: "${LNMP_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/php:${LNMP_PHP_VERSION:-7.4.7}-unit-alpine"
    volumes:
      - ./config/${LNMP_NGINX_UNIT_CONF:-nginx-unit}:/etc/nginx-unit:cached
      # ./path/unit-init-conf:/docker-entrypoint.d
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
      - ./log/nginx-unit:/var/log/nginx-unit:delegated
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro,cached
      - ./config/php/${LNMP_PHP_EXTRA_INI:-docker-php.ini}:/usr/local/etc/php/conf.d/docker-php.ini:ro,cached
      - ./log/php:/var/log/php:delegated
      - type: volume
        source: nginx_unit_state-data
        target: /usr/local/nginx-unit/state
    networks:
      - backend
      - frontend
    command:
      - unitd
      - --no-daemon
      - --user
      - root
      - --group
      - root
      - --log
      - /var/log/nginx-unit/nginx-unit.log
      # --state
      # /usr/local/nginx-unit/state
      - --control
      - unix:/usr/local/nginx-unit/control.unit.sock
volumes:
  nginx_unit_state-data:
    << : *default-common-label
