kind: Service
apiVersion: v1
metadata:
  name: registry
  labels:
    app: lnmp
    tier: registry
    version: {{ .Chart.Version }}
spec:
  # type: NodePort
  selector:
    app: lnmp
    tier: registry
    version: {{ .Chart.Version }}
  ports:
  - name: http
    port: 443
    # nodePort: 443
