kind: ConfigMap
apiVersion: v1
metadata:
  name: lnmp-registry-conf-{{ .Chart.Version }}
  labels:
    app: lnmp
    tier: registry
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" -}}
  config.yml: | {{ range .Files.Lines "config/config.development.yml" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  config.yml: | {{ range .Files.Lines "config/config.testing.yml" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  config.yml: | {{ range .Files.Lines "config/config.staging.yml" }}
    {{ . }}{{ end }}
  {{- else -}}
  config.yml: | {{ range .Files.Lines "config/config.production.yml" }}
    {{ . }}{{ end }}
  {{- end }}
