kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: lnmp-registry-tls-{{ .Chart.Version }}
  labels:
    app: lnmp
    tier: registry
    version: {{ .Chart.Version }}
data:
  tls.crt: {{ .Files.Get "config/ssl/public.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/ssl/private.key" | b64enc }}
