resources:
  - base/prometheus-serviceMonitorEtcd.yaml
namespace: monitoring
secretGenerator:
  - name: etcd-client-tls
    files:
      - certs/ca.pem
      - certs/cert.pem
      - certs/key.pem
generatorOptions:
  disableNameSuffixHash: true
