kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: etcd
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: ca.pem
          name: etcd-client-tls
      cert:
        secret:
          key: cert.pem
          name: etcd-client-tls
      keySecret:
        key: key.pem
        name: etcd-client-tls
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd
