apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: registry
  name: registry
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: debug
  jobLabel: app
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: registry-metrics
