version: "3.7"

services:
  nfs:
    restart: "no"
    image: erichough/nfs-server
    volumes:
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs:/nfs
      - ${APP_ROOT:-../app}:/nfs/lnmp/app
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/mysql:/nfs/lnmp/mysql
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/redis:/nfs/lnmp/redis
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/registry:/nfs/lnmp/registry
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/lnmp/log:/nfs/lnmp/log
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/kubernetes_pv:/nfs/kubernetes_pv
      - ${NFS_DATA_ROOT:-./nfs-data}/nfs/kubernetes_csi:/nfs/kubernetes_csi
    env_file:
      - ./.env
    # cap_add:
    #  - SYS_ADMIN
    privileged: true
    ports:
      # - "111:111"
      # - "111:111/udp"
      # nfs4 only need open 2049/tcp port
      - "2049:2049"
      # - "2049:2049/udp"
      # - "32765:32765"
      # - "32765:32765/udp"
      # - "32767:32767"
      # - "32767:32767/udp"

volumes:
  nfs-volume:
