kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
spec:
  template:
    spec:
      containers:
      - name: registry
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
        ports:
        - name: debug
          containerPort: 5001
        livenessProbe:
          httpGet:
            path: /metrics
            port: debug
            scheme: HTTP
      volumes:
      - name: config
        configMap:
          name: "registry-config"
