apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
spec:
  ports:
  - name: https-metrics
    port: 10257
    protocol: TCP
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
subsets:
  - addresses:
    - ip: 192.168.199.100
    ports:
      - name: https-metrics
        port: 10257
