version: "3.7"

x-build:
  &default-build
  # Dockerfile: my.Dockerfile
  args:
    ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
    NPM_REGISTRY: https://registry.npm.taobao.org # https://registry.npmjs.org

x-build-debian:
  &default-build-debian
  # Dockerfile: my.Dockerfile
  args:
    DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
    DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org

x-labels:
  &default-labels
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=self_build

services:
  {{example}}:
    << : *default-labels
    build:
      << : *default-labels
      << : *default-build
      # << : *default-build-debian
      context: ./vendor/${LREW_EXAMPLE_VENDOR:-lrew}/{{example}}
