apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-app
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: code-data
      env: production
  storageClassName: "hostpath"
