bases:
- ../../base
- ../../../secret
resources:
- pvc.yaml
- lnmp-nginx.service.yaml
configMapGenerator:
- name: lnmp-nginx-conf
  files:
  - nginx.conf=config/nginx.production.conf
- name: lnmp-nginx-conf.d
  files:
  - config/conf.d/t.khs1994.com.production.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
patches:
  # - hostpath.patch.yaml
generatorOptions:
  labels:
    app: lnmp
    tier: nginx
