kind: Deployment
apiVersion: apps/v1
metadata:
  name: harbor-jobservice
spec:
  template:
    spec:
      initContainers:
      - name: chmod
        image: busybox
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - "chown 10000:10000 /var/log/jobs"
        volumeMounts:
        - name: job-logs
          mountPath: /var/log/jobs
