# 适用于 Docker for macOS 的 PV 定义文件

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-app-development
  labels:
    type: local
    app: lnmp
    tier: code-data
    env: development
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/username/app-development
    type: DirectoryOrCreate
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-mysql-data-development
  labels:
    type: local
    app: lnmp
    tier: mysql
    env: development
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce    # 被单个节点mount为读写rw模式
    # - ReadOnlyMany   # 被多个节点mount为只读ro模式
    # - ReadWriteMany  # 被多个节点mount为读写rw模式
  persistentVolumeReclaimPolicy: Retain
  # Retain 允许用户手动回收
  # Recycle 删除 PV 上的数据
  # Delete 删除 PV
  hostPath:
    path: /Users/username/.docker/Volumes/lnmp-mysql-data-development
    type: DirectoryOrCreate
  storageClassName: hostpath

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-redis-data-development
  labels:
    type: local
    app: lnmp
    tier: redis
    env: development
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/username/.docker/Volumes/lnmp-redis-data-development
    type: DirectoryOrCreate
  storageClassName: hostpath

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-log-development
  labels:
    type: local
    app: lnmp
    tier: log
    env: development
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/username/.docker/Volumes/lnmp-log-development
    type: DirectoryOrCreate
  storageClassName: hostpath
