secretGenerator:
  - name: harbor-notary-server
    files:
    - certs/ca.crt
    - certs/tls.crt
    - certs/tls.key
    - certs/server.json
    - certs/signer.json
commonLabels:
  app: "harbor"
  component: notary
generatorOptions:
  disableNameSuffixHash: true
