kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/khs1994-docker-lnmp/postgresql
