apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-controller-manager
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    port: https-metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: ca.pem
          name: kube-controller-manager-tls
      cert:
        secret:
          key: cert.pem
          name: kube-controller-manager-tls
      keySecret:
        key: key.pem
        name: kube-controller-manager-tls
      insecureSkipVerify: true
