apiVersion: v1
kind: Secret
metadata:
  name: "postgresql-secret"
  labels:
    app: "postgresql"
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2hhbmdlaXQ="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "postgresql"
  labels:
    app: "postgresql"
spec:
  replicas: 1
  serviceName: "postgresql"
  selector:
    matchLabels:
      app: "postgresql"
  template:
    metadata:
      labels:
        app: "postgresql"
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
      - name: "change-permission-of-directory"
        image: "busybox:latest"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "chown -R 999:999 /var/lib/postgresql/data"]
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
          subPath:
      - name: "remove-lost-found"
        image: goharbor/harbor-db:v1.9.3
        imagePullPolicy: IfNotPresent
        command: ["rm", "-Rf", "/var/lib/postgresql/data/lost+found"]
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
          subPath:
      containers:
      - name: database
        image: goharbor/harbor-db:v1.9.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 1
          periodSeconds: 10
        envFrom:
          - secretRef:
              name: "postgresql-secret"
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
          subPath:
      volumes:
        - name: database-data
          persistentVolumeClaim:
              claimName: postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: "postgresql"
  labels:
    app: "postgresql"
spec:
  ports:
    - port: 5432
  selector:
    app: "postgresql"
