apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-mysql-password-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  password: {{ .Values.mysql.password | b64enc }}
