apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: lnmp
    tier: mysql
    version: {{ .Chart.Version }}
spec:
  # type: NodePort
  selector:
    app: lnmp
    tier: mysql
    version: {{ .Chart.Version }}
  ports:
  - name: mysql
    port: 3306
    # nodePort: 3306
    # protocol: TCP
    # targetPort: 3306
  clusterIP: None
