apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
    env: {{ .Values.APP_ENV }}
spec:
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
      env: {{ .Values.APP_ENV }}
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  {{if .Values.nfs.enabled -}}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{- else -}}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
