apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-redis-conf-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" }}
  redis.conf: | {{ range .Files.Lines "config/redis.development.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  redis.conf: | {{ range .Files.Lines "config/redis.testing.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  redis.conf: | {{ range .Files.Lines "config/redis.staging.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "production" -}}
  redis.conf: | {{ range .Files.Lines "config/redis.production.conf" }}
    {{ . }}{{ end }}
  {{- end }}
