apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-redis-data
  labels:
    app: lnmp
    tier: redis
    env: {{ .Values.APP_ENV }}
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: redis
      env: {{ .Values.APP_ENV }}
  resources:
    requests:
      storage: 20Gi
  {{if .Values.nfs.enabled -}}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{- else -}}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
