kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 192.168.199.100
healthzBindAddress: 192.168.199.100:10256
metricsBindAddress: 192.168.199.100:10249
enableProfiling: true
clusterCIDR: 10.244.0.0/16
hostnameOverride: windows
portRange: ""
mode: "kernelspace"
# mode: "iptables"
iptables:
  masqueradeAll: false
ipvs:
  scheduler: rr
  excludeCIDRs: []
