apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
      env: production
  storageClassName: "hostpath"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-log
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: log
      env: production
  storageClassName: "hostpath"
