# namePrefix: prod-
# commonLabels:
# commonAnnotations:
bases:
- ../../base
resources:
- pvc.yaml
patches:
- lnmp-mysql.yaml
# - hostpath.patch.yaml
configMapGenerator:
- name: lnmp-mysql-cnf-prod
  files:
  - docker.cnf=config/docker.production.cnf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
secretGenerator:
- name: lnmp-mysql-password
  literals:
  - password=mytest
generatorOptions:
  labels:
    app: lnmp
    tier: mysql
