resources:
- tekton.yaml
- dashboard.yaml
# configMapGenerator:
#   - name: config-artifact-bucket
#     namespace: tekton-pipelines
#     literals:
#       - location=gs://bucket-name
#       - location=s3://mybucket
#       - bucket.service.account.secret.name=tekton-storage
#       - bucket.service.account.secret.key=boto-config
#       - bucket.service.account.field.name=BOTO_CONFIG
#   - name: config-artifact-pvc
#     namespace: tekton-pipelines
#     literals:
#       - size=5Gi
#       - storageClassName=storage-class-name
# secretGenerator:
#   - name: tekton-storage
#     namespace: tekton-pipelines
#     type: kubernetes.io/opaque
#     files:
#       - boto-config
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:9ba9c755e868942143868dbbc7a0d9ab29241014833dd0a7ac6156d66e45fe9b
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-dashboard
    digest: sha256:9ba9c755e868942143868dbbc7a0d9ab29241014833dd0a7ac6156d66e45fe9b
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.13.2@sha256:cd3c83221f860746c9d757a6750f762a8a7351a7513acfc1bfc661ba2f265764
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-webhook
    digest: sha256:cd3c83221f860746c9d757a6750f762a8a7351a7513acfc1bfc661ba2f265764
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.13.2@sha256:c44f6810aa63cd96210c832034c4a6dbe593c5df85a3cbb22fffef46a1596f58
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-controller
    digest: sha256:c44f6810aa63cd96210c832034c4a6dbe593c5df85a3cbb22fffef46a1596f58
