version: "3.7"

x-common:
  &default-common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &default-common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mongodb:
    << : *default-common
    image: ${LNMP_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/mongo:${LNMP_MONGODB_VERSION:-4.2.7}
    volumes:
      - ./config/mongodb/${LNMP_MONGODB_CONF:-mongod.conf}:/etc/mongod.conf:ro,cached
      - type: volume
        source: mongodb-data
        target: /data/db
      - ./log/mongodb/mongo.log:/var/log/mongodb/mongo.log:delegated
    ports:
      - "${LNMP_MONGODB_PORT:-127.0.0.1:27017}:27017"
    command: ["mongod","--config","/etc/mongod.conf"]

volumes:
  mongodb-data:
    << : *default-common-label
