apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-env-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  TZ: {{ .Values.TZ }}
  APP_ENV: {{ .Values.APP_ENV }}
  APP_LOG: {{ .Values.APP_LOG }}
  LOG_CHANNEL: {{ .Values.LOG_CHANNEL }}
  LNMP_XDEBUG_REMOTE_HOST: 192.168.199.100
  LNMP_XDEBUG_REMOTE_PORT: 9001
  LNMP_OPCACHE_ENABLE: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-php-conf-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" }}
  php.ini: | {{ range .Files.Lines "config/php/ini/php.development.ini" }}
    {{ . }}{{ end }}
  docker-xdebug.ini: | {{ range .Files.Lines "config/php/docker-xdebug.ini" }}
    {{ . }}{{ end }}
  zz-docker.conf: | {{ range .Files.Lines "config/php/zz-docker.development.conf" }}
    {{ . }}{{ end }}
  composer.config.json: | {{ range .Files.Lines "config/php/composer/config.development.json" }}
    {{ . }}{{ end }}
  docker.ini: | {{ range .Files.Lines "config/php/conf.d/docker.development.ini" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  php.ini: | {{ range .Files.Lines "config/php/ini/php.testing.ini" }}
    {{ . }}{{ end }}
  docker-xdebug.ini: | {{ range .Files.Lines "config/php/docker-xdebug.ini" }}
    {{ . }}{{ end }}
  zz-docker.conf: | {{ range .Files.Lines "config/php/zz-docker.testing.conf" }}
    {{ . }}{{ end }}
  composer.config.json: | {{ range .Files.Lines "config/php/composer/config.testing.json" }}
    {{ . }}{{ end }}
  docker.ini: | {{ range .Files.Lines "config/php/conf.d/docker.testing.ini" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  php.ini: | {{ range .Files.Lines "config/php/ini/php.staging.ini" }}
    {{ . }}{{ end }}
  docker-xdebug.ini: | {{ range .Files.Lines "config/php/docker-xdebug.ini" }}
    {{ . }}{{ end }}
  zz-docker.conf: | {{ range .Files.Lines "config/php/zz-docker.staging.conf" }}
    {{ . }}{{ end }}
  composer.config.json: | {{ range .Files.Lines "config/php/composer/config.staging.json" }}
    {{ . }}{{ end }}
  docker.ini: | {{ range .Files.Lines "config/php/conf.d/docker.staging.ini" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "production" -}}
  php.ini: | {{ range .Files.Lines "config/php/ini/php.production.ini" }}
    {{ . }}{{ end }}
  docker-xdebug.ini: | {{ range .Files.Lines "config/php/docker-xdebug.ini" }}
    {{ . }}{{ end }}
  zz-docker.conf: | {{ range .Files.Lines "config/php/zz-docker.production.conf" }}
    {{ . }}{{ end }}
  composer.config.json: | {{ range .Files.Lines "config/php/composer/config.production.json" }}
    {{ . }}{{ end }}
  docker.ini: | {{ range .Files.Lines "config/php/conf.d/docker.production.ini" }}
    {{ . }}{{ end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-nginx-conf-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{if eq .Values.APP_ENV "development" }}
  nginx.conf: | {{ range .Files.Lines "config/nginx/nginx.development.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  nginx.conf: | {{ range .Files.Lines "config/nginx/nginx.testing.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  nginx.conf: | {{ range .Files.Lines "config/nginx/nginx.staging.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "production" -}}
  nginx.conf: | {{ range .Files.Lines "config/nginx/nginx.production.conf" }}
    {{ . }}{{ end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-nginx-conf.d-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" }}
  www.t.khs1994.com.conf: | {{ range .Files.Lines "config/nginx/conf.d/t.khs1994.com.development.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  www.t.khs1994.com.conf: | {{ range .Files.Lines "config/nginx/conf.d/t.khs1994.com.testing.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  www.t.khs1994.com.conf: | {{ range .Files.Lines "config/nginx/conf.d/t.khs1994.com.staging.conf" }}
    {{ . }}{{ end }}
  {{- else if eq .Values.APP_ENV "production" -}}
  www.t.khs1994.com.conf: | {{ range .Files.Lines "config/nginx/conf.d/t.khs1994.com.production.conf" }}
    {{ . }}{{ end }}
  {{- end }}
