apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-nginx-khs1994-com-tls-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" }}
  t.khs1994.com.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.development/t.khs1994.com.crt" | b64enc }}
  t.khs1994.com.key: {{ .Files.Get "config/nginx/conf.d/ssl.development/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  t.khs1994.com.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.testing/t.khs1994.com.crt" | b64enc }}
  t.khs1994.com.key: {{ .Files.Get "config/nginx/conf.d/ssl.testing/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  t.khs1994.com.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.staging/t.khs1994.com.crt" | b64enc }}
  t.khs1994.com.key: {{ .Files.Get "config/nginx/conf.d/ssl.staging/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "production" -}}
  t.khs1994.com.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.crt" | b64enc }}
  t.khs1994.com.key: {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.key" | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-ingress-tls-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  {{ if eq .Values.APP_ENV "development" }}
  tls.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.development/t.khs1994.com.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/nginx/conf.d/ssl.development/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "testing" -}}
  tls.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.testing/t.khs1994.com.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/nginx/conf.d/ssl.testing/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "staging" -}}
  tls.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.staging/t.khs1994.com.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/nginx/conf.d/ssl.staging/t.khs1994.com.key" | b64enc }}
  {{- else if eq .Values.APP_ENV "production" -}}
  tls.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.key" | b64enc }}
  {{- end }}
