apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
        - name: lnmp-mysql-cnf
          configMap:
            name: lnmp-mysql-cnf
            items:
            - key: docker.cnf
              path: docker.cnf
