apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-mysql-data
  labels:
    type: local
    app: lnmp
    tier: mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem # Filesystem | Block
  accessModes:
    # - ReadWriteOnce
    # - ReadOnlyMany   # 被多个节点mount为只读ro模式 ROX
    - ReadWriteMany  # 被多个节点mount为读写rw模式 RWX
  persistentVolumeReclaimPolicy: Retain
  # Retain 允许用户手动回收
  # Recycle 删除 PV 上的数据 deprecated
  # Delete 删除 PV

  # Currently, only NFS and HostPath support recycling.
  # AWS EBS, GCE PD, Azure Disk, and Cinder volumes support deletion.
  nfs:
    # FIXME: use the right IP
    server: 192.168.199.100
    path: "/lnmp/mysql"
  storageClassName: slow
  mountOptions:
    # - hard
    # - nfsvers=4.1
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
spec:
  accessModes:
    - ReadWriteMany
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-log
  labels:
    type: local
    app: lnmp
    tier: log
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # FIXME: use the right IP
    server: 192.168.199.100
    path: "/lnmp/log"
  storageClassName: slow
  mountOptions:
    # - hard
    # - nfsvers=4.1
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-log
  labels:
    app: lnmp
    tier: log
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: lnmp
      tier: log
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
