kind: Service
apiVersion: v1
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
  - name: http
    port: 5000
    targetPort: http
  selector:
    app: registry

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: registry
          image: registry
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 5000
          # - name: debug
          #   containerPort: 5001
          volumeMounts:
            - mountPath: /var/lib/registry
              name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: registry-data
