name: lwpm-dist-file

on:
  push:
    branches:
      - "19.03"

jobs:
  lwpm-dist-file:
    name: lwpm-dist-file
    runs-on: ${{ matrix.os }}-latest
    if: |
      contains( github.event.head_commit.message, '[lwpm dist]')
    env:
      LWPM_DOCKER_USERNAME: khs1994
      LWPM_DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      LWPM_DIST_ONLY: 'true'
      LWPM_DOCKER_REGISTRY: registry-1.docker.io
    strategy:
      matrix:
        os: ["windows","ubuntu"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          repository: khs1994-docker/lnmp
          fetch-depth: 1
          # ref: 19.03
          path: lnmp
      - name: handle-conmon
        shell: pwsh
        if: matrix.os == 'ubuntu' &&
            contains( github.event.head_commit.message, '[k8s]')
        env:
          VERSION: 2.0.15
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install conmon@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    conmon@${env:VERSION}
      - name: handle-containerd
        shell: pwsh
        if: matrix.os == 'ubuntu' &&
            contains( github.event.head_commit.message, '[k8s]')
        env:
          VERSION: 1.3.4
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install containerd@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    containerd@${env:VERSION}
      - name: handle-crictl
        shell: pwsh
        if: matrix.os == 'windows' &&
            contains( github.event.head_commit.message, '[k8s]')
        env:
          VERSION: 1.18.0
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install crictl@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    crictl@${env:VERSION}
      - name: handle-etcd
        if: endsWith('a', 'b')
        shell: pwsh
        env:
          VERSION: 3.4.9
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install etcd@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    etcd@${env:VERSION}
      - name: handle-helm
        if: endsWith('a', 'b')
        shell: pwsh
        env:
          VERSION: 3.2.0
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install helm@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    helm@${env:VERSION}
      - name: handle-runc
        shell: pwsh
        if: matrix.os == 'windows' &&
            contains( github.event.head_commit.message, '[k8s]')
        env:
          VERSION: 1.0.0-rc10
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install runc@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    runc@${env:VERSION}
      - name: handle-runsc
        shell: pwsh
        if: matrix.os == 'ubuntu' &&
            contains( github.event.head_commit.message, '[k8s]')
        env:
          VERSION: nightly
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install runsc@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    runsc@${env:VERSION}

      - name: handle-compose
        shell: pwsh
        if: |
          matrix.os == 'ubuntu' &&
            contains( github.event.head_commit.message, '[compose]')
        env:
          VERSION: 1.25.5
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install compose@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    compose@${env:VERSION}

      - name: handle-jx
        shell: pwsh
        if: |
          matrix.os == 'ubuntu' &&
            contains( github.event.head_commit.message, '[jx]')
        env:
          VERSION: 2.1.33
        run: |
          ./lnmp/windows/lnmp-windows-pm.ps1 install jx@${env:VERSION}
          ./lnmp/windows/lnmp-windows-pm.ps1 push    jx@${env:VERSION}
