on:
  push:
    tags:
      - '*'
    branches:
      - 19.03
    # paths:
    #   - '/.github/actions/*'

name: Sync Actions

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: |
      contains( github.ref, 'refs/tags/' )
      || contains( github.event.head_commit.message, '[sync actions]')
      || contains( github.event.head_commit.message, '[sync action]')
    steps:
      - run: echo "sync continue !"
  sync-actions:
    runs-on: ubuntu-latest
    needs: skip-ci
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: build-actions-setup-php
      run: |
        cd .github/actions/setup-php
        sed -i 's#node_modules##g' .gitignore
        npm i
    - name: sync-actions-setup-php
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/actions-setup-php
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: .github/actions/setup-php
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: build-actions-setup-docker
      run: |
        cd .github/actions/setup-docker
        sed -i 's#node_modules##g' .gitignore
        npm i
    - name: sync-actions-setup-docker
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/docker-practice/actions-setup-docker
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: .github/actions/setup-docker
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: build-actions-setup-lnmp
      run: |
        cd .github/actions/setup-lnmp
        sed -i 's#node_modules##g' .gitignore
        npm i
    - name: sync-actions-setup-lnmp
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/actions-setup-lnmp
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: .github/actions/setup-lnmp
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
