on:
  push:
    # Sequence of patterns matched against refs/tags
    # tags:
    # - '*'
    # Sequence of patterns matched against refs/heads
    branches:
    - 19.03-pre
    # - 'releases/*'   # Push events to branches matching refs/heads/releases/*

name: Sync PHP

jobs:
  sync-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: sync-php
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/php
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: dockerfile/php
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
