# commit mesage include [skip sync] to skip ci

on:
  push:
    tags:
    - '*'
    branches:
    - "19.03"

name: Sync Git

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: |
      contains( github.ref, 'refs/tags/' )
      || contains( github.event.head_commit.message, '[sync git]')
    steps:
      - run: echo "sync continue !"
  sync-git:
    runs-on: ubuntu-latest
    needs: skip-ci
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: sync-acme.sh
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/acme-docker
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: dockerfile/acme.sh
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-ci
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/ci
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: drone
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-kubernetes
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/lnmp-k8s
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: kubernetes
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-node-demo
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/node-demo
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: app/node-demo
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-php-demo
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/php-demo
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: app/demo
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-buildx
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/docker-practice/buildx
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: dockerfile/buildkit
        PCIT_MESSAGE: commit by ci
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-laravel-demo
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/laravel-demo
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: app/laravel-demo
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-kube-nginx
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/kube-nginx
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: kubernetes/kube-nginx
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-k8s-ci-demo
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/k8s-demo
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: kubernetes/demo/ci
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-docker-image-sync
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/docker-image-sync
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: dockerfile/sync
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-nginx
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/nginx
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: dockerfile/nginx
        PCIT_MESSAGE: Sync from khs1994-docker/lnmp@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
